name: generateVeille

on:
#  schedule:
 #   - cron: '42 */6 * * *'  # Exécute le workflow toutes les heures
  workflow_dispatch:  # Permet de lancer le workflow manuellement

jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r scripts/veille/requirements.txt
            
      - name: Run shell script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
            source venv/bin/activate
            chmod +x scripts/veille/generateVeille.sh
            scripts/veille/generateVeille.sh
            ls -la
          
            
      