name: generateVeille

on:
#  schedule:
 #   - cron: '42 */6 * * *'  # Exécute le workflow toutes les heures
  workflow_dispatch:  # Permet de lancer le workflow manuellement

jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r scripts/veille/requirements.txt
            
      - name: Run Veille for Gemini Flash 2.0
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
            source venv/bin/activate
            venv/bin/python3 scripts/veille/pocGemini.py -o _posts/fr/`date +'%Y-%m'`
            ls -la _posts/fr/`date +'%Y-%m'`
          
      - name: Commit and push changes
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d')
          echo "Ajout des fichiers générés le $CURRENT_DATE"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add _posts/fr/`date +'%Y-%m'`
          git commit -m "Ajout des fichiers générés le $CURRENT_DATE"
          git push
            
      